[theme]
base = "dark"

primaryColor = "#7C83FD"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#131927"
textColor = "#F4F6FA"

font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"

baseRadius = "0.75rem"
buttonRadius = "0.65rem"

borderColor = "#252D3D"
showWidgetBorder = true
showSidebarBorder = true

[server]
headless = true